name = "cf-fullstack-backend"
compatibility_date = "2024-03-26"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "my-d1-db"
database_id = "92862384-241a-43c6-b88e-418a76f6df37"

[dev]
port = 8787
